Function SetISOFileName ; Distro2Check (Name of the Distro), ISO2Check2 (The ISO File name before extraction), Download2Get (Download Link), Path2Name (Final destination/Name of File), GimmeSize (Size of the File), Config2Use (Config File to Write To), File2Check (file to check for before adding Menu entry), Homepage, OfficialName
 
     !insertmacro SetISOFileNames "--- Ubuntu 32/64 Bit ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""
	 
 !insertmacro SetISOFileNames "Ubuntu" "*.iso" "http://www.ubuntu.com/start-download?distro=desktop&bits=32&release=saucy" "casper" "linux.cfg" "http://www.ubuntu.com/desktop" "Ubuntu"
 !insertmacro SetISOFileNames "Edubuntu" "*.iso" "cdimage.ubuntu.com/edubuntu/releases/saucy/release/edubuntu-13.10-dvd-i386.iso" "casper" "linux.cfg" "http://edubuntu.org" "Edubuntu" 
 !insertmacro SetISOFileNames "Kubuntu" "*.iso" "http://cdimage.ubuntu.com/kubuntu/releases/saucy/release/kubuntu-13.10-desktop-i386.iso" "casper" "linux.cfg" "http://www.kubuntu.org" "Kubuntu"
 !insertmacro SetISOFileNames "Lubuntu" "*.iso" "http://cdimage.ubuntu.com/lubuntu/releases/saucy/release/lubuntu-13.10-desktop-i386.iso" "casper" "linux.cfg" "http://lubuntu.net" "Lubuntu" 
 !insertmacro SetISOFileNames "Xubuntu" "*.iso" "http://cdimage.ubuntu.com/xubuntu/releases/saucy/release/xubuntu-13.10-desktop-i386.iso" "casper" "linux.cfg" "http://xubuntu.org" "Xubuntu"
 !insertmacro SetISOFileNames "Ubuntu Gnome" "*.iso" "http://cdimage.ubuntu.com/ubuntu-gnome/releases/raring/release/ubuntu-gnome-13.04-desktop-i386.iso" "casper" "linux.cfg" "http://www.ubuntugnome.org" "Ubuntu Gnome"
 !insertmacro SetISOFileNames "Ubuntu Server" "*.iso" "http://www.ubuntu.com/start-download?distro=server&bits=32&release=saucy" "NULL" "linux.cfg" "http://www.ubuntu.com/server" "Ubuntu Server"
 !insertmacro SetISOFileNames "Ubuntu Studio" "*.iso" "http://cdimage.ubuntu.com/ubuntustudio/releases/saucy/release/ubuntustudio-13.10-dvd-i386.iso" "casper" "linux.cfg" "http://ubuntustudio.org" "Ubuntu Studio" 
;REVISIT !insertmacro SetISOFileNames "Ubuntu Rescue Remix (System Rescue)" "*.iso" "http://ubuntu-rescue-remix.org/Download" "NULL" "system.cfg" "http://ubuntu-rescue-remix.org" "URR"

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Linux Mint 32/64 Bit ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""  
   
 !insertmacro SetISOFileNames "Linux Mint" "*.iso" "http://www.linuxmint.com/download.php" "casper" "linux.cfg" "http://www.linuxmint.com" "Linux Mint"

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Debian Live 32/64 Bit ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""
 
 !insertmacro SetISOFileNames "Debian Live" "*.iso" "http://cdimage.debian.org/cdimage/release/current-live/amd64/iso-hybrid/debian-live-7.0.0-amd64-gnome-desktop.iso" "NULL" "linux.cfg" "http://live.debian.net" "Debian Live"

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Fedora 32/64 Bit ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""
 
 !insertmacro SetISOFileNames "Fedora" "*.iso" "http://fedoraproject.org/en/get-fedora#desktops" "NULL" "linux.cfg" "http://fedoraproject.org" "Fedora"	 

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- OpenSUSE ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""  

 !insertmacro SetISOFileNames "OpenSUSE 32bit" "*.iso" "http://suse.mirrors.tds.net/pub/opensuse/distribution/13.1/iso/openSUSE-13.1-GNOME-Live-x86_64.iso" "NULL" "linux.cfg" "http://software.opensuse.org" "OpenSUSE"	 
 !insertmacro SetISOFileNames "OpenSUSE 64bit" "*.iso" "http://suse.mirrors.tds.net/pub/opensuse/distribution/13.1/iso/openSUSE-13.1-GNOME-Live-i686.iso" "NULL" "linux.cfg" "http://software.opensuse.org" "OpenSUSE"	 
 
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Puppy Linux Based ---" "" "" "" "" "" ""
	 !insertmacro SetISOFileNames "" "" "" "" "" "" ""  
	 
 !insertmacro SetISOFileNames "DPup Exprimo" "*.iso" "http://www.smokey01.com/pemasu/DpupSqueeze5X/DpupExprimo5X3621/squeeze-5.X.3.6.2.1-SCSI.iso" "NULL" "linux.cfg" "http://www.murga-linux.com/puppy/viewtopic.php?t=81528" "Dpup"
 !insertmacro SetISOFileNames "Fatdog64" "*.iso" "http://ftp.nluug.nl/ibiblio/distributions/fatdog/iso/Fatdog64-601-Firefox.iso" "NULL" "linux.cfg" "http://www.puppylinuxforum.org/thread-180.html" "Fatdog64"
 !insertmacro SetISOFileNames "Lucid Puppy Linux" "*.iso" "http://distro.ibiblio.org/pub/linux/distributions/puppylinux/puppy-5.2.8/lupu-528.005.iso" "NULL" "linux.cfg" "http://www.puppylinux.org" "Puppy Linux"
 !insertmacro SetISOFileNames "Precise Puppy Linux" "*.iso" "http://distro.ibiblio.org/quirky/precise-5.4.1/precise-5.4.1.iso" "NULL" "linux.cfg" "http://bkhome.org/blog/?viewDetailed=03063" "Precise Puppy"
 !insertmacro SetISOFileNames "Racy Puppy Linux" "*.iso" "http://distro.ibiblio.org/quirky/racy-5.3/racy-5.3.iso" "NULL" "linux.cfg" "http://puppylinux.org/main/New%20Racy%20Puppy.htm" "Racy Puppy Linux" 
 !insertmacro SetISOFileNames "Slacko Puppy" "*.iso" "http://ftp.nluug.nl/ftp/pub/os/Linux/distr/puppylinux/puppy-5.3.3/slacko-5.3.3-4g-SCSI.iso" "NULL" "linux.cfg" "http://puppylinux.org/wikka/Puppy53" "Slacko Puppy 5.3" 
 !insertmacro SetISOFileNames "Wary Puppy Linux" "*.iso" "http://distro.ibiblio.org/quirky/wary-5.5/wary-5.5.iso" "NULL" "linux.cfg" "http://puppylinux.org/main/Long-Term-Supported%20WaryPuppy.htm" "Wary Puppy Linux"	 


     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Netbook Distributions 32/64 Bit---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
	 
 !insertmacro SetISOFileNames "EasyPeasy (NetBook Distro)" "*.iso" "http://sourceforge.net/projects/ubuntu-eee/files/EasyPeasy/EasyPeasy-1.6.iso/download" "NULL" "netbook.cfg" "http://www.geteasypeasy.com" "EasyPeasy"
 !insertmacro SetISOFileNames "Jolicloud (NetBook Distro)" "*.iso" "http://www.jolicloud.com/jolios/download/jolicloud-iso/thank-you" "NULL" "netbook.cfg" "http://www.jolicloud.com" "Jolicloud"
 !insertmacro SetISOFileNames "xPUD (Netbook Distro)" "*.iso" "http://xpud.googlecode.com/files/xpud-0.9.2.iso" "NULL" "netbook.cfg" "http://www.xpud.org" "xPud"

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Other Distros 32/64 Bit ---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""	 
	 
 !insertmacro SetISOFileNames "AntiX" "*.iso" "http://sourceforge.net/projects/antix-linux/files/Final/antiX-13.1/antiX-13.1_386-full.iso/download" "NULL" "linux.cfg" "http://sourceforge.net/projects/antix-linux/" "AntiX"   
 !insertmacro SetISOFileNames "Archlinux" "*.iso" "http://mirrors.us.kernel.org/archlinux/iso/latest/archlinux-2013.02.01-dual.iso" "NULL" "linux.cfg" "http://www.archlinux.org" "Archlinux"  
 !insertmacro SetISOFileNames "Bodhi" "*.iso" "http://sourceforge.net/projects/bodhilinux/files/latest/download" "NULL" "linux.cfg" "http://www.bodhilinux.com" "Bodhi"  
 !insertmacro SetISOFileNames "CAELinux (Computer Aided Engineering)" "*.iso" "ftp://cae-linux:salome@caelinux.dyndns.org/distrib/caelinux2011/caelinux2011.iso" "NULL" "linux.cfg" "http://caelinux.com/CMS/" "CAELinux"  
;Revisit !insertmacro SetISOFileNames "Calculate Linux Desktop" "*.iso" "ftp://ftp.gtlib.gatech.edu/pub/calculate/CLDG/12.0/i686/cldg-12.0-i686.iso" "NULL" "linux.cfg" "http://www.calculate-linux.org/" "Calculate Linux"
 !insertmacro SetISOFileNames "CentOS" "*.iso" "http://mirror.cisp.com/CentOS/6.4/isos/i386/CentOS-6.4-i386-LiveCD.iso" "NULL" "linux.cfg" "http://www.centos.org" "CentOS"
 !insertmacro SetISOFileNames "Crunchbang" "*.iso" "http://crunchbang.org/download/" "NULL" "linux.cfg" "http://crunchbang.org" "Crunchbang"
 !insertmacro SetISOFileNames "Damn Small Linux (DSL)" "*.iso" "ftp://distro.ibiblio.org/pub/linux/distributions/damnsmall/current/dsl-4.4.10-initrd.iso" "NULL" "linux.cfg" "http://www.damnsmalllinux.org" "DSL"
 !insertmacro SetISOFileNames "Elementary OS" "*.iso" "http://sourceforge.net/projects/elementaryos/files/stable/elementaryos-stable-amd64.20130810.iso/download" "NULL" "linux.cfg" "http://elementaryos.org/" "Elementary OS"
;Revisit !insertmacro SetISOFileNames "Dreamlinux" "*.iso" "http://download.linux-live-cd.org/iso/Dreamlinux/Dreamlinux-5.iso" "NULL" "linux.cfg" "http://www.dreamlinux.info/" "Dreamlinux" 
 !insertmacro SetISOFileNames "Fuduntu" "*.iso" "http://sourceforge.net/projects/fuduntu/files/latest/download" "NULL" "linux.cfg" "http://www.fuduntu.org/" "Fuduntu"
 !insertmacro SetISOFileNames "Fusion Linux" "*.iso" "http://fusionlinux.org/downloads/" "NULL" "linux.cfg" "http://fusionlinux.org/" "Fusion Linux"
 !insertmacro SetISOFileNames "JustBrowsing" "*.iso" "http://sourceforge.net/projects/justbrowsing/files/justbrowsing_20140124.iso/download" "NULL" "linux.cfg" "http://justbrowsing.info/" "JustBrowsing"
 !insertmacro SetISOFileNames "KNOPPIX" "*.iso" "http://ftp.knoppix.nl/os/Linux/distr/knoppix/KNOPPIX_V7.2.0CD-2013-06-16-EN.iso" "NULL" "linux.cfg" "http://knopper.net" "KNOPPIX"
 !insertmacro SetISOFileNames "KXStudio" "*.iso" "http://sourceforge.net/projects/kxstudio/files/latest/download" "NULL" "linux.cfg" "http://kxstudio.sourceforge.net" "KXStudio"
 !insertmacro SetISOFileNames "Liberte (Anonymous Browsing)" "*.zip" "http://softlayer-dal.dl.sourceforge.net/project/liberte/2012.3/liberte-2012.3.zip" "NULL" "linux.cfg" "http://dee.su/liberte" "Liberte"
;Revisit !insertmacro SetISOFileNames "Linux Lite" "*.iso" "http://superb-dca2.dl.sourceforge.net/project/linuxlite/1.0.6/linux-lite-1.0.6-32bit.iso" "NULL" "linux.cfg" "https://www.linuxliteos.com/" "Linux Lite"
 !insertmacro SetISOFileNames "Linux Secure Remix" "*.iso" "http://sourceforge.net/projects/linux-secure/files/latest/download" "NULL" "linux.cfg" "https://help.ubuntu.com/community/UbuntuSecureRemix" "Ubuntu Secure"
 !insertmacro SetISOFileNames "LXLE Desktop" "*.iso" "http://www.lxle.net/download" "casper" "linux.cfg" "http://lxle.net/" "LXLE Desktop" 
 !insertmacro SetISOFileNames "Mageia Live CD" "*.iso" "http://mirrors.kernel.org/mageia/iso/2/Mageia-2-dual-CD/Mageia-2-dual-CD.iso" "NULL" "linux.cfg" "http://www.mageia.org" "Mageia"
 !insertmacro SetISOFileNames "Mandriva 2011" "*.iso" "ftp://ftp.uwsg.indiana.edu/linux/mandrake/official/iso/2011/Mandriva.2011.x86_64.1.iso" "NULL" "linux.cfg" "http://www.mandriva.com" "Mandriva"
 !insertmacro SetISOFileNames "Manjaro" "*.iso" "http://manjaro.org/get-manjaro/" "NULL" "linux.cfg" "http://manjaro.org" "Manjaro"
 !insertmacro SetISOFileNames "Mythbuntu" "*.iso" "http://download.mythbuntu.org/?file=mythbuntu-12.04.3-desktop-i386.iso" "NULL" "linux.cfg" "http://mythbuntu.org/" "Mythbuntu"
;Revisit !insertmacro SetISOFileNames "MultiCore" "*.iso" "http://distro.ibiblio.org/pub/linux/distributions/tinycorelinux/3.x/release/multicore-current.iso" "NULL" "linux.cfg" "http://www.tinycorelinux.com" "MultiCore"
 !insertmacro SetISOFileNames "Netrunner" "*.iso" "http://www.netrunner-os.com/download/" "NULL" "linux.cfg" "http://www.netrunner-os.com" "Netrunner"
 !insertmacro SetISOFileNames "OSGeo Live" "*.iso" "http://sourceforge.net/projects/osgeo-live/files/latest/download" "NULL" "linux.cfg" "http://live.osgeo.org" "OSGeo Live"
 !insertmacro SetISOFileNames "PCLinuxOS" "*.iso" "http://www.pclinuxos.com/?page_id=10" "NULL" "linux.cfg" "http://www.pclinuxos.com" "PCLinuxOS"
 !insertmacro SetISOFileNames "Pear Linux" "*.iso" "http://sourceforge.net/projects/pearlinuxprivat/files/Pear%20OS%207%20Release/pearos7-amd64.iso/download" "NULL" "linux.cfg" "http://pearlinux.fr" "Pear Linux"
 !insertmacro SetISOFileNames "Peppermint" "*.iso" "http://peppermintos.com/download/" "NULL" "linux.cfg" "http://peppermintos.com" "Peppermint"
 !insertmacro SetISOFileNames "Pinguy OS" "*.iso" "http://sourceforge.net/projects/pinguy-os/files/latest/download" "NULL" "linux.cfg" "http://pinguy-os.sourceforge.net" "Pinguy" 
 !insertmacro SetISOFileNames "Porteus" "*.iso" "http://www.ponce.cc/porteus/i486/current/" "NULL" "linux.cfg" "https://porteus.org/" "Porteus"
 !insertmacro SetISOFileNames "SalineOS" "*.iso" "http://www.salineos.com/server/SalineOS-1.0-i386-PSE.iso" "NULL" "linux.cfg" "http://www.salineos.com" "SalineOS"
 ;REVISIT !insertmacro SetISOFileNames "Samurai-WTF" "*.iso" "http://sourceforge.net/projects/samurai/files/samurai/samurai-0.9.5/samurai-0.9.5.iso/download" "NULL" "linux.cfg" "http://samurai.inguardians.com/" "Samurai"
 ;REVISIT !insertmacro SetISOFileNames "Scientific Linux CERN" "*.iso" "http://linux.web.cern.ch/linux/scientific6/docs/repository/cern/slc6X/x86_64/images/boot.iso" "NULL" "linux.cfg" "http://linux.web.cern.ch/linux/" "Scientific Linux"
 ;REVISIT uses grub !insertmacro SetISOFileNames "Semplice Linux" "*.iso" "http://semplice-linux.org/download/" "NULL" "linux.cfg" "http://semplice-linux.org" "Semplice Linux" 
 !insertmacro SetISOFileNames "SLAX (Tiny Slackware Based Distro)" "*.iso" "http://www.slax.org/download.php" "NULL" "linux.cfg" "http://slax.org" "SLAX"
 !insertmacro SetISOFileNames "Slitaz (Another Tiny Distro)" "*.iso" "http://distro.ibiblio.org/slitaz/iso/4.0/slitaz-4.0.iso" "NULL" "linux.cfg" "http://www.slitaz.org" "SliTaZ"
 !insertmacro SetISOFileNames "Sn0wL1nuX" "*.iso" "http://sourceforge.net/projects/sn0wl1nux/files/latest/download" "NULL" "linux.cfg" "http://luninuxos.com" "Sn0wL1nuX" 
 !insertmacro SetISOFileNames "SolydX" "*.iso" "http://downloads.solydxk.com/solydx32_latest.iso" "NULL" "linux.cfg" "http://solydxk.com" "SolydX Linux" 
 !insertmacro SetISOFileNames "Sparky Linux" "*.iso" "http://sourceforge.net/projects/sparkylinux/files/latest/download" "NULL" "linux.cfg" "http://sparkylinux.org" "Sparky Linux" 
 !insertmacro SetISOFileNames "Sugar on a Stick" "*.iso" "http://dl.fedoraproject.org/pub/alt/releases/19/Spins/i386/Fedora-Live-SoaS-i686-19-1.iso" "NULL" "linux.cfg" "http://wiki.sugarlabs.org/go/Sugar_on_a_Stick" "Sugar On A Stick"
 !insertmacro SetISOFileNames "Tails (Anonymous Browsing)" "*.iso" "http://dl.amnesia.boum.org/tails/stable/" "NULL" "linux.cfg" "http://amnesia.boum.org" "Tails"
 !insertmacro SetISOFileNames "Terralinux" "*.iso" "http://sourceforge.net/projects/terralinuxos/files/latest/download" "NULL" "linux.cfg" "http://terralinux.blogspot.com/" "Terralinux"
 !insertmacro SetISOFileNames "TinyCore (A Tiny Linux Distribution)" "*.iso" "http://distro.ibiblio.org/tinycorelinux/5.x/x86/release/TinyCore-5.0.2.iso" "NULL" "linux.cfg" "http://www.tinycorelinux.com" "TinyCore"
 !insertmacro SetISOFileNames "Uberstudent" "*.iso" "http://sourceforge.net/projects/uberstudent/files/Releases/Plato/uberstudent-3.0-xfce-i386.iso/download" "NULL" "linux.cfg" "http://uberstudent.com/" "Uberstudent"
 !insertmacro SetISOFileNames "Ultimate Edition 3" "*.iso" "http://sourceforge.net/projects/ultimateedition/files/latest/download" "NULL" "linux.cfg" "http://ultimateedition.info" "Ultimate Edition"
 !insertmacro SetISOFileNames "Web Converger (Web Kiosk)" "*.iso" "http://dl.webconverger.com/latest.iso" "NULL" "linux.cfg" "http://webconverger.com/" "Web Converger" 
 !insertmacro SetISOFileNames "XBMCbuntu" "*.iso" "http://mirrors.xbmc.org/releases/XBMCbuntu/" "NULL" "linux.cfg" "http://xbmc.org/" "XBMC" 
 !insertmacro SetISOFileNames "Zorin OS Core" "*.iso" "http://zorin-os.com/free.html" "NULL" "linux.cfg" "http://zorin-os.com/" "Zorin OS"
 
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Antivirus Tools ---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
	 
 !insertmacro SetISOFileNames "Acronis Antimalware CD" "*.iso" "http://download.acronis.com/iso/AcronisAntimalwareScanCD.iso" "NULL" "antivirus.cfg" "http://kb.acronis.com/content/18647" "Acronis"
 !insertmacro SetISOFileNames "Antivirus Live CD (Virus Scanner)" "*.iso" "http://sourceforge.net/projects/antiviruslivecd/files/latest/download" "NULL" "antivirus.cfg" "http://antiviruslivecd.4mlinux.com" "Antivirus Live CD"  
 !insertmacro SetISOFileNames "AOSS (Malware Scanner)" "*.iso" "http://download.pctools.com/mirror/AOSS.iso" "NULL" "antivirus.cfg" "http://www.pctools.com/aoss/" "AOSS"  
 !insertmacro SetISOFileNames "AVG Rescue CD (Antivirus Scanner)" "*.iso" "http://www.avg.com/us-en/download-file-cd-arl-iso" "NULL" "antivirus.cfg" "http://www.avg.com" "AVG Rescue CD"
 !insertmacro SetISOFileNames "AVIRA AntiVir Rescue CD (Virus Scanner)" "*.iso" "http://www.avira.com/en/download/product/avira-rescue-system" "NULL" "antivirus.cfg" "http://www.avira.com" "Avira"
 !insertmacro SetISOFileNames "Bitdefender Rescue Disk (Antivirus Scanner)" "*.iso" "http://download.bitdefender.com/rescue_cd/bitdefender-rescue-cd.iso" "NULL" "antivirus.cfg" "http://bitdefender.com" "Bitdefender"
 !insertmacro SetISOFileNames "Comodo Rescue Disk (Antivirus Scanner)" "*.iso" "http://help.comodo.com/topic-170-1-493-5214-Downloading-Comodo-Rescue-Disk.html" "NULL" "antivirus.cfg" "http://help.comodo.com/topic-170-1-493-5208-Introduction-to-Comodo-Rescue-Disk.html" "Comodo" 
 !insertmacro SetISOFileNames "Dr.Web Live CD" "*.iso" "http://download.geo.drweb.com/pub/drweb/livecd/drweb-livecd-602.iso" "NULL" "antivirus.cfg" "http://www.freedrweb.com/livecd/" "Dr.Web"  
 !insertmacro SetISOFileNames "Desinfec't 2013" "t*.iso" "NONE" "NULL" "antivirus.cfg" "" ""
 !insertmacro SetISOFileNames "F-Secure Rescue CD" "*.iso" "http://download.f-secure.com/estore/rescue-cd-3.16-52606.iso" "NULL" "antivirus.cfg" "http://www.f-secure.com/en_EMEA-Labs/security-threats/tools/rescue-cd/" "F-Secure Rescue CD"
 !insertmacro SetISOFileNames "GDATA Rescue CD" "*.iso" "http://www.softpedia.com/get/Antivirus/G-Data-BootCD.shtml" "NULL" "antivirus.cfg" "http://www.gdatasoftware.com" "GDATA"
 !insertmacro SetISOFileNames "Kaspersky Rescue Disk (Antivirus Scanner)" "kav_rescue_10.iso" "http://rescuedisk.kaspersky-labs.com/rescuedisk/updatable/kav_rescue_10.iso" "NULL" "antivirus.cfg" "http://support.kaspersky.com/viruses/rescuedisk" "Kaspersky"
 !insertmacro SetISOFileNames "Panda SafeCD" "*.iso" "http://www.pandasecurity.com/resources/sop/SafeCD/PandaSafeCD.iso" "NULL" "antivirus.cfg" "http://www.pandasecurity.com/usa/homeusers/support/card?id=80152" "Panda Safe CD"
;REVISIT !insertmacro SetISOFileNames "Vba32 Rescue" "*.iso" "ftp://anti-virus.by/pub/vbarescue.iso" "NULL" "antivirus.cfg" "http://www.anti-virus.by/en/vba32rescue.shtml" "Vba32 Rescue"
 !insertmacro SetISOFileNames "Windows Defender Offline" "*.iso" "http://go.microsoft.com/fwlink/?LinkID=234123" "NULL" "antivirus.cfg" "http://windows.microsoft.com/en-US/windows/what-is-windows-defender-offline" "Windows Defender"
 
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- System Tools ---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
	 
 !insertmacro SetISOFileNames "Acronis True Image" "*.iso" "" "NULL" "system.cfg" "http://www.acronis.com" "Acronis True-Image" 
 !insertmacro SetISOFileNames "BackBox (Penetration Testing)" "*.iso" "http://backbox.mirror.garr.it/mirrors/backbox/backbox-3.0-i386.iso" "NULL" "system.cfg" "http://www.backbox.org/" "BackBox"
 !insertmacro SetISOFileNames "BackTrack5 (Penetration Testing)" "*.iso" "http://www.backtrack-linux.org/downloads/" "NULL" "system.cfg" "http://www.backtrack-linux.org" "Backtrack"
 !insertmacro SetISOFileNames "Bugtraq 2 (Penetration Testing)" "*.iso" "http://www.bugtraq-team.com:6014/isos/bugtraq-II_bw-u-gnome_x32.iso" "NULL" "system.cfg" "http://bugtraq-team.com" "Bugtraq II"
 !insertmacro SetISOFileNames "Boot Repair Disk 32bit" "*.iso" "http://sourceforge.net/projects/boot-repair-cd/files/boot-repair-disk-32bit.iso/download" "NULL" "system.cfg" "http://sourceforge.net/projects/boot-repair-cd/" "Boot Repair Disk"
 !insertmacro SetISOFileNames "Boot Repair Disk 64bit" "*.iso" "http://sourceforge.net/projects/boot-repair-cd/files/boot-repair-disk-64bit.iso/download" "NULL" "system.cfg" "http://sourceforge.net/projects/boot-repair-cd/" "Boot Repair Disk"
;REVISIT !insertmacro SetISOFileNames "Caine (Forensics)" "*.iso" "http://www.caine-live.net/Downloads/caine3.0.iso" "NULL" "system.cfg" "http://www.caine-live.net/" "Caine" 
 !insertmacro SetISOFileNames "Clonezilla (Backup + Clone Tool)" "*.iso" "http://sourceforge.net/projects/clonezilla/files/latest/download" "NULL" "system.cfg" "http://clonezilla.org" "Clonezilla"
 !insertmacro SetISOFileNames "DBAN (Hard Drive Nuker)" "*.iso" "http://sourceforge.net/projects/dban/files/dban/dban-2.2.7/dban-2.2.7_i586.iso/download" "NULL" "system.cfg" "http://www.dban.org" "DBAN"
 !insertmacro SetISOFileNames "Deft (Forensics)" "*.iso" "http://www.deftlinux.net/download/" "NULL" "system.cfg" "http://www.deftlinux.net/" "Deft"
 !insertmacro SetISOFileNames "DRBL (Diskless Remote Boot in Linux)" "*.iso" "http://sourceforge.net/projects/drbl/files/latest/download" "NULL" "system.cfg" "http://drbl.sourceforge.net" "DRBL"	 
 !insertmacro SetISOFileNames "EASEUS Disk Copy (Disk Cloning Tool)" "*.iso" "http://majorgeeks.com/EaseUs_Disk_Copy_d4845.html" "NULL" "system.cfg" "http://www.easeus.com" "EASEUS Disk Copy"
 !insertmacro SetISOFileNames "FreeDOS (Balder img)" "*.img" "http://www.finnix.org/files/balder10.img" "NULL" "system.cfg" "http://www.finnix.org/Balder" "Finnix Balder"
 !insertmacro SetISOFileNames "G4L (Ghost For Linux)" "*.iso" "http://sourceforge.net/projects/g4l/files/latest/download" "NULL" "system.cfg" "http://sourceforge.net/projects/g4l/" "G4L"
 !insertmacro SetISOFileNames "GParted (Partition Tools)" "*.iso" "http://sourceforge.net/projects/gparted/files/latest" "NULL" "system.cfg" "http://gparted.sourceforge.net" "gParted"
 !insertmacro SetISOFileNames "GRML (system rescue)" "*.iso" "http://download.grml.org/grml96-full_2013.02.iso" "NULL" "system.cfg" "http://grml.org" "GRML"
 !insertmacro SetISOFileNames "HDT (Hardware Detection Tool)" "*.img" "http://www.hdt-project.org/raw-attachment/wiki/hdt-0.5.0/hdt-0.5.2.img" "NULL" "system.cfg" "http://hdt-project.org" "HDT" 
 !insertmacro SetISOFileNames "Kali (Penetration Testing)" "*.iso" "http://www.kali.org/downloads/" "NULL" "system.cfg" "http://www.kali.org/" "Kali"
 !insertmacro SetISOFileNames "Memtest86+ (Memory Testing Tool)" "*.zip" "http://www.memtest.org/download/5.01/memtest86+-5.01.zip" "NULL" "system.cfg" "http://www.memtest.org" "Memtest86+" 
 !insertmacro SetISOFileNames "Matriux (Penetration Testing)" "*.iso" "http://sourceforge.net/projects/matriux/files/latest/download" "NULL" "system.cfg" "http://www.matriux.com" "Matriux"
 !insertmacro SetISOFileNames "Offline NT Password & Registry Editor" "*.iso" "http://pogostick.net/~pnh/ntpasswd/cd110511.zip" "NULL" "system.cfg" "http://www.pogostick.net/~pnh/ntpasswd/" "Offline NT"
;REVISIT !insertmacro SetISOFileNames "OpenMediaVault" "*.iso" "http://sourceforge.net/projects/openmediavault/files/0.5.0.24/" "NULL" "system.cfg" "http://www.openmediavault.org/" "OpenMediaVault"
 !insertmacro SetISOFileNames "Ophcrack (no tables)" "*.iso" "http://sourceforge.net/projects/ophcrack/files/ophcrack-livecd/3.6.0/ophcrack-notables-livecd-3.6.0.iso/download" "NULL" "system.cfg" "http://ophcrack.sourceforge.net" "Ophcrack"
 !insertmacro SetISOFileNames "Ophcrack XP (Password Finder)" "*.iso" "http://downloads.sourceforge.net/ophcrack/ophcrack-xp-livecd-3.6.0.iso" "NULL" "system.cfg" "http://ophcrack.sourceforge.net" "Ophcrack"
 !insertmacro SetISOFileNames "Ophcrack Vista/7 (Password Finder)" "*.iso" "http://downloads.sourceforge.net/ophcrack/ophcrack-vista-livecd-3.6.0.iso" "NULL" "system.cfg" "http://ophcrack.sourceforge.net" "Ophcrack"
 !insertmacro SetISOFileNames "Parted Magic (Partition Tools)" "*.iso" "NONE" "NULL" "system.cfg" "http://partedmagic.com" "Parted Magic"
 !insertmacro SetISOFileNames "Partition Wizard (Partition Tools)" "*.iso" "http://www.partitionwizard.com/download/pwhe7.iso" "NULL" "system.cfg" "http://www.partitionwizard.com" "Partition Wizard"
 !insertmacro SetISOFileNames "PING (Partimg Is Not Ghost)" "*.iso" "http://ping.windowsdream.com/ping/Releases/3.00.04/PING-3.00.iso" "NULL" "system.cfg" "http://ping.windowsdream.com" "PING"
 !insertmacro SetISOFileNames "Rescatux" "*.iso" "http://sourceforge.net/projects/rescatux.berlios/files/rescatux_cdrom_usb_hybrid_i386_486-amd64_0.30b3.iso/download" "NULL" "system.cfg" "http://www.supergrubdisk.org/rescatux/" "Rescatux" 
 !insertmacro SetISOFileNames "Redo Backup And Recovery (Recovery Tools)" "*.iso" "http://sourceforge.net/projects/redobackup/files/latest/download" "NULL" "system.cfg" "http://redobackup.org" "RedoBackup"
 !insertmacro SetISOFileNames "REMnux (Reverse Engineer Malware)" "*.iso" "http://sourceforge.net/projects/remnux/files/version4/remnux-4.0-live-cd.iso/download" "NULL" "system.cfg" "http://zeltser.com/remnux/" "Remnux"
 !insertmacro SetISOFileNames "Rip Linux (Recovery Distro)" "*.iso" "http://www.tux.org/pub/people/kent-robotti/looplinux/rip/" "NULL" "system.cfg" "http://www.tux.org/pub/people/kent-robotti/looplinux/rip/" "RIP Linux"
 !insertmacro SetISOFileNames "System Rescue CD" "*.iso" "http://sourceforge.net/projects/systemrescuecd/files/latest/download" "NULL" "system.cfg" "http://www.sysresccd.org" "System Rescue"
 !insertmacro SetISOFileNames "Trinity Rescue Kit" "*.iso" "ftp://ftp.osuosl.org/pub/trk/trinity-rescue-kit.3.4-build-372.iso" "NULL" "system.cfg" "http://trinityhome.org" "TRK"
 !insertmacro SetISOFileNames "Ultimate Boot CD (Diagnostics Tools)" "*.iso" "http://ftp.cc.uoc.gr/mirrors/linux/ubcd/ubcd521.iso" "NULL" "system.cfg" "http://www.ultimatebootcd.com" "Ultimate Boot CD"
 !insertmacro SetISOFileNames "Wifislax (Wireless Penetration Testing)" "*.iso" "http://downloadwireless.net/isos/wifislax-4-7-final.iso" "NULL" "system.cfg" "http://www.wifislax.com/" "Wifislax"
;REVISIT filename contains spaces !insertmacro SetISOFileNames "XIAOPAN (Wireless Penetration Testing)" "*.iso" "http://sourceforge.net/projects/xiaopanos/files/latest/download" "NULL" "system.cfg" "http://xiaopan.co/forums/" "XIAOPAN"

     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Other OS/Tools ---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
	 
 !insertmacro SetISOFileNames "Linux Live Tools for OCZ" "*.iso" "NONE" "NULL" "other.cfg" "http://www.ocztechnologyforum.com/forum/showthread.php?99275-NEW!-Bootable-Linux-based-tools-for-OCZ-SSD-s" "OCZ" 
 !insertmacro SetISOFileNames "Falcon 4 Boot CD" "*.iso" "NONE" "NULL" "other.cfg" "" ""
 !insertmacro SetISOFileNames "Hiren's Boot CD" "*.iso" "NONE" "NULL" "other.cfg" "" ""
 !insertmacro SetISOFileNames "Kon-Boot FREE" "*.zip" "https://www.dropbox.com/s/f5i4g9vlmwoxrtp/kon-boot1.1-free.zip" "NULL" "other.cfg" "http://www.piotrbania.com/all/kon-boot/" "Kon-Boot" 
 !insertmacro SetISOFileNames "Kon-Boot Purchased" "*.exe" "NONE" "NULL" "other.cfg" "http://www.piotrbania.com/all/kon-boot/" "Kon-Boot" 

 !insertmacro SetISOFileNames "Windows Vista/7/8 Installer" "*.iso" "NONE" "NULL" "other.cfg" "" ""
 !insertmacro SetISOFileNames "Windows XP Installer" "*.iso" "NONE" "NULL" "menu.lst" "" ""  
 
     !insertmacro SetISOFileNames "" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "--- Unlisted Bootable ISOs ---" "" "" "" "" "" ""
     !insertmacro SetISOFileNames "" "" "" "" "" "" "" 	
	 
 !insertmacro SetISOFileNames "Try Unlisted ISO (via SYSLINUX)" "*.iso" "NONE" "NULL" "unlisted.cfg" "" "" 	 
 !insertmacro SetISOFileNames "Try Unlisted ISO (GRUB)" "*.iso" "NONE" "NULL" "menu.lst" "" "" 
 !insertmacro SetISOFileNames "Try Unlisted ISO (GRUB from RAM)" "*.iso" "NONE" "NULL" "menu.lst" "" ""  
 
FunctionEnd
